### ISSUE TITLE
Passing params to controller action from view via button_to

### ISSUE THREAD

**Issue by sauchak** [sauchak/sauchak_trading_co#1]
User Story: Making a trade offer on an item in another user's listing

NameError in Listings#index // ```undefined local variable or method `listing_trades' for #<#<Class:0x007fca0c9980d0>:0x007fca05357100> ```

-when I replace it with the path,  `listing_trades_path` I get a different error:
ActionController::UrlGenerationError in Listings#index // ```No route matches {:action=>"create", :controller=>"trades"} missing required keys: [:listing_id]```

Checking rake routes prefixes and (trades#create) Controller#Action exists
I have a feeling it's all because of a greater issue of my TradesController being incomplete (sorry Dean, I have failed you. I cannot seem to get the logic down.)

**Comment by tambling** [comment]
@sauchak Can you post a couple of screenshots of the code where you think the error might be happening?

**Comment by sauchak** [comment]
![listings view](https://i.imgur.com/qfOtSXy.png)
^^^This is what I'm referencing in the issue. But I am also struggling with the picture below:
![trades controller](https://i.imgur.com/M9tOivP.png)

**Comment by tambling** [comment]
So yeah, you need to make sure that you have `resources :trades` in your `routes.rb`, then run `rake routes` and see which path points to `trades#create` (probably `POST` to `/trades`, named as `trades` (as in `trades_path`)).

**Comment by sauchak** [comment]
```resources :trades``` is nested within ```resources :listing``` so the rake routes list ```listing_trades``` points to ```trade#creates``` which gives me the error: 

ActionController::UrlGenerationError in Listings#index 
No route matches {:action=>"create", :controller=>"trades"} missing required keys: [:listing_id]

I'm assuming this has to do with the params in the controller??

**Comment by tambling** [comment]
Yeah, on line 18 in `_listing.html.erb`, you'll want to specify that you want to follow `listing_trades_path(listing)`: that you want to `POST` to `/listings/:listing_id/trades`, where `listing_id` is the ID of the `listing` you pass in.

Also, in `TradesController`, the `create` method should be where you actually create the trade– that isn't happening in your code right now.

**Comment by sauchak** [comment]
Well that worked. Thank you. 

Now to work on the ```TradesController```!

**Comment by tambling** [comment]
:pray:
